name: unit tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - NOTICES
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - NOTICES
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies with pip
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install .[all]

      - name: Run formatters
        shell: bash -l {0}
        run: |
          flake8 .
          black --check .
          isort --check-only .

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          pytest
